name: thellmbook
channels:
  - pytorch
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - accelerate=1.12.0=pyhcf101f3_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py310hd5e7861_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - anyio=4.12.1=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-timeout=5.0.1=pyhcf101f3_2
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=h1ddaa69_0
  - aws-c-cal=0.9.13=h6ee9776_1
  - aws-c-common=0.12.6=hc919400_0
  - aws-c-compression=0.3.1=h16f91aa_9
  - aws-c-event-stream=0.5.7=h9ae9c55_1
  - aws-c-http=0.10.7=h5928ca5_5
  - aws-c-io=0.23.3=hbe03c90_5
  - aws-c-mqtt=0.13.3=haf5c5c8_11
  - aws-c-s3=0.11.3=h8da9771_1
  - aws-c-sdkutils=0.2.4=h16f91aa_4
  - aws-checksums=0.2.7=h16f91aa_5
  - aws-crt-cpp=0.35.4=h74951b9_0
  - aws-sdk-cpp=1.11.606=h4e1b0f7_10
  - azure-core-cpp=1.16.1=h88fedcc_0
  - azure-identity-cpp=1.13.2=h853621b_1
  - azure-storage-blobs-cpp=12.16.0=h6507aac_0
  - azure-storage-common-cpp=12.12.0=ha416c23_0
  - azure-storage-files-datalake-cpp=12.14.0=hcfc4f22_0
  - backports.zstd=1.3.0=py310h2d60bed_0
  - brotli-python=1.2.0=py310h6123dab_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.10.19=py310hd8ed1ab_3
  - datasets=4.5.0=pyhcf101f3_0
  - debugpy=1.8.19=py310h7b404bc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhcf101f3_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.20.3=pyhd8ed1ab_0
  - frozenlist=1.7.0=py310ha18c8e3_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py310h1b1a8f9_2
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - hf-xet=1.2.1=py310h6ce4931_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=1.3.4=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h38cb7af_0
  - idna=3.11=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.18=hdfa7624_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=23.0.0=h4365f54_1_cpu
  - libarrow-acero=23.0.0=h6de58dd_1_cpu
  - libarrow-compute=23.0.0=h45df96a_1_cpu
  - libarrow-dataset=23.0.0=h6de58dd_1_cpu
  - libarrow-substrait=23.0.0=hb5627e6_1_cpu
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.18.0=he38603e_0
  - libcxx=21.1.8=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=hcf2aa1b_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.2=h8088a28_0
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=pthreads_h735b822_4
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=23.0.0=hcc2992d_1_cpu
  - libpng=1.6.54=h132b30e_0
  - libprotobuf=6.31.1=h98f38fd_4
  - libre2-11=2025.11.05=h91c62da_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.2=h1ae2325_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h4030677_1
  - libutf8proc=2.11.3=h2431656_0
  - libwebp=1.6.0=hc0253d1_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h8d039ee_1
  - libxml2-16=2.15.1=h5ef1a60_1
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=15.0.7=h7cfbb63_0
  - lz4-c=1.10.0=h286801f_1
  - markupsafe=3.0.3=py310hf4fd40f_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.7.0=py310hdf731dd_0
  - multiprocess=0.70.18=py310hf151d32_2
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.12.0=h784d473_1
  - numpy=2.2.6=py310h4d83441_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.1=hd24854e_1
  - orc=2.2.2=hac85105_0
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.3.3=py310h25f4b65_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.1.0=py310hc037f36_0
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py310hc74094e_0
  - psutil=7.2.1=py310haea493c_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=23.0.0=py310hb6292c7_0
  - pyarrow-core=23.0.0=py310h7f23fb1_0_cpu
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=hcd7f573_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.10.19=hd8ed1ab_3
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py310h36bdd5b_1
  - python_abi=3.10=8_cp310
  - pytorch=2.5.1=py3.10_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310hf4fd40f_0
  - pyzmq=27.1.0=py310hc4a7dca_0
  - re2=2025.11.05=h64b956e_0
  - readline=8.3=h46df422_0
  - regex=2026.1.15=py310h72544b6_0
  - requests=2.32.5=pyhcf101f3_1
  - safetensors=0.7.0=py310h53169e7_0
  - setuptools=80.10.1=pyh332efcf_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh2585a3b_105
  - tk=8.6.13=h010d191_3
  - tokenizers=0.22.2=py310h8c671df_0
  - torchaudio=2.5.1=py310_cpu
  - torchvision=0.20.1=py310_cpu
  - tornado=6.5.4=py310hfe3a0ae_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=5.0.0=pyhd8ed1ab_0
  - typer-slim=0.21.1=pyhcf101f3_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wcwidth=0.4.0=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xxhash=0.8.3=haa4e116_0
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=py310hf4fd40f_0
  - zeromq=4.3.5=h888dc83_9
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.3.2=hed4e4f5_1
  - zstd=1.5.7=hbf9d68e_6
prefix: /Users/ruchira/miniforge3/envs/thellmbook
